apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10
  strategy:
    # value: [RollingUpdate, Recreate]
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80


# kubectl  create -f rolling_update.yml --record
# kubectl set image  deploy/nginx-deployment nginx=nginx:1.9.1
# kubectl rollout history deploy/nginx-deployment
# kubectl rollout undo deploy/nginx-deployment --to-revision=1
