kubectl create secret generic db-user-pass --from-file=./username.txt --from-file=./password.txt

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm


